# Generated by Django 4.0.6 on 2023-12-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='touser',
        ),
    ]
