# Generated by Django 5.0.3 on 2024-03-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
